# Generated by Django 5.2.4 on 2025-10-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eSports', '0002_remove_produto_estoque_remove_produto_imagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Visitas do Site',
                'verbose_name_plural': 'Visitas do Site',
            },
        ),
    ]
