# Generated by Django 5.2.4 on 2025-10-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eSports', '0003_sitevisits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jogador',
            options={'verbose_name': 'Jogador da Equipe', 'verbose_name_plural': 'Jogadores da Equipe'},
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='funcao',
        ),
        migrations.AddField(
            model_name='jogador',
            name='cla',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Clã (Clash Royale)'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Foto do jogador (formato quadrado)', null=True, upload_to='jogadores/'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='nivel_cr',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nível (Clash Royale)'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='trofeus_cr',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Troféus (Clash Royale)'),
        ),
    ]
