# Generated by Django 5.2.4 on 2025-10-25 18:12

import ckeditor_uploader.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eSports', '0004_alter_jogador_options_remove_jogador_funcao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='conteudo',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Conteúdo da Matéria'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data_publicacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem_destaque',
            field=models.ImageField(blank=True, null=True, upload_to='noticias_destaques/'),
        ),
    ]
