# Generated by Django 5.2.4 on 2025-10-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eSports', '0005_alter_noticia_conteudo_alter_noticia_data_publicacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(blank=True, help_text="Ex: 'Atualizações', 'Competitivo'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='resumo',
            field=models.TextField(default='', help_text='Um parágrafo curto que aparece na home e na lista de notícias.', max_length=300),
            preserve_default=False,
        ),
    ]
