# Generated by Django 5.2.4 on 2025-10-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eSports', '0006_noticia_categoria_noticia_resumo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partida',
            options={'ordering': ['data_hora']},
        ),
        migrations.AddField(
            model_name='partida',
            name='link_vod',
            field=models.URLField(blank=True, null=True, verbose_name='Link do VOD (YouTube, Twitch)'),
        ),
        migrations.AddField(
            model_name='partida',
            name='thumbnail_vod',
            field=models.ImageField(blank=True, null=True, upload_to='partidas_thumbnails/', verbose_name='Thumbnail do VOD'),
        ),
        migrations.AddField(
            model_name='partida',
            name='twitch_channel',
            field=models.CharField(blank=True, help_text="Apenas o NOME do canal. Ex: 'reidatorre'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partida',
            name='youtube_video_id',
            field=models.CharField(blank=True, help_text="Apenas o ID do vídeo. Ex: 'dQw4w9WgXcQ'", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='data_hora',
            field=models.DateTimeField(verbose_name='Data e Hora'),
        ),
    ]
