# Generated by Django 5.2.4 on 2025-10-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eSports', '0007_alter_partida_options_partida_link_vod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacaoproduto',
            name='frete_gratis',
            field=models.BooleanField(default=False, verbose_name='Tem frete grátis?'),
        ),
        migrations.AddField(
            model_name='variacaoproduto',
            name='max_parcelas_sem_juros',
            field=models.IntegerField(default=1, help_text='Coloque 1 se não houver parcelamento sem juros', verbose_name='Nº de parcelas sem juros'),
        ),
        migrations.AddField(
            model_name='variacaoproduto',
            name='preco_antigo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deixe em branco se não houver desconto.', max_digits=10, null=True, verbose_name='Preço Antigo (Riscado)'),
        ),
        migrations.AlterField(
            model_name='variacaoproduto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Atual'),
        ),
    ]
