# Generated by Django 5.2.4 on 2025-10-26 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eSports', '0008_variacaoproduto_frete_gratis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='is_lancamento',
            field=models.BooleanField(default=False, verbose_name='É Lançamento?'),
        ),
    ]
