# Generated by Django 5.2.4 on 2025-10-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eSports', '0009_produto_is_lancamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='youtube_video_id',
        ),
        migrations.AddField(
            model_name='partida',
            name='link_live_youtube',
            field=models.URLField(blank=True, help_text="Cole o LINK COMPLETO da live do YouTube aqui. Ex: 'https://www.youtube.com/watch?v=...'", max_length=255, null=True, verbose_name='Link da Live (YouTube)'),
        ),
    ]
