# Generated by Django 5.2.4 on 2025-10-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eSports', '0010_remove_partida_youtube_video_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='link_live_youtube',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='twitch_channel',
        ),
        migrations.AddField(
            model_name='partida',
            name='iframe_live',
            field=models.TextField(blank=True, help_text='Cole o CÓDIGO HTML COMPLETO do iframe (ex: <iframe src=.../iframe>)', null=True, verbose_name='Código Iframe da Live'),
        ),
    ]
