# Generated by Django 5.2.4 on 2025-10-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eSports', '0011_remove_partida_link_live_youtube_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partida',
            options={'ordering': ['data_hora'], 'verbose_name': 'Partida', 'verbose_name_plural': 'Partidas'},
        ),
        migrations.AlterField(
            model_name='partida',
            name='iframe_live',
            field=models.TextField(blank=True, help_text="\n        Cole o <iframe> COMPLETO aqui (YouTube ou Twitch). \n        IMPORTANTE: Apague o width/height e adicione \n        style='position: absolute; top: 0; left: 0; width: 100%; height: 100%;'\n        ", null=True, verbose_name='Código Iframe da Live (Player Principal)'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='link_vod',
            field=models.URLField(blank=True, help_text="Link completo da gravação (VOD) após a partida ser 'Finalizada'.", null=True, verbose_name='Link do VOD (Gravação)'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='status',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('finalizada', 'Finalizada'), ('ao_vivo', 'Ao Vivo')], default='agendada', help_text="Mude para 'Ao Vivo' para esta partida aparecer no Player Principal.", max_length=20),
        ),
        migrations.AlterField(
            model_name='partida',
            name='thumbnail_vod',
            field=models.ImageField(blank=True, null=True, upload_to='partidas_thumbnails/', verbose_name='Thumbnail do VOD (Capa do Card)'),
        ),
    ]
