# Generated by Django 5.2.4 on 2025-10-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eSports', '0012_alter_partida_options_alter_partida_iframe_live_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='iframe_live',
        ),
        migrations.AddField(
            model_name='partida',
            name='plataforma_live',
            field=models.CharField(blank=True, choices=[('twitch', 'Twitch'), ('youtube', 'YouTube')], help_text='Escolha onde a live será transmitida.', max_length=20, null=True, verbose_name='Plataforma da Live'),
        ),
        migrations.AddField(
            model_name='partida',
            name='twitch_channel',
            field=models.CharField(blank=True, help_text="APENAS o nome do canal. Ex: 'ratolunaticotv'", max_length=100, null=True, verbose_name='Nome do Canal (Twitch)'),
        ),
        migrations.AddField(
            model_name='partida',
            name='youtube_video_id',
            field=models.CharField(blank=True, help_text="APENAS o ID do vídeo/live. Ex: 'dQw4w9WgXcQ'", max_length=100, null=True, verbose_name='ID do Vídeo/Live (YouTube)'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='link_vod',
            field=models.URLField(blank=True, help_text="Link completo da gravação após a partida ser 'Finalizada'.", null=True, verbose_name='Link do VOD (Gravação)'),
        ),
    ]
