# Generated by Django 5.2.4 on 2025-10-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eSports', '0013_remove_partida_iframe_live_partida_plataforma_live_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='plataforma_live',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='twitch_channel',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='youtube_video_id',
        ),
        migrations.AddField(
            model_name='partida',
            name='iframe_live',
            field=models.TextField(blank=True, help_text="\n        Cole o <iframe> COMPLETO aqui (YouTube ou Twitch). \n        IMPORTANTE: Apague o width/height e adicione \n        style='position: absolute; top: 0; left: 0; width: 100%; height: 100%;'\n        ", null=True, verbose_name='Código Iframe da Live (Player Principal)'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='link_vod',
            field=models.URLField(blank=True, help_text="Link completo da gravação (VOD) após a partida ser 'Finalizada'.", null=True, verbose_name='Link do VOD (Gravação)'),
        ),
    ]
